In [1]:
import numpy as np 

In [4]:
np_posistion = np.loadtxt('D:\\BÀI TẬP\\BÀI TẬP CHƯƠNG 3\\Bài 3.8\\positions.txt',delimiter=',',encoding='utf-8-sig',dtype=str)
np_posistion

array(['GK', 'M', 'A', ..., 'D', 'D', 'M'], dtype='<U2')

In [5]:
np_height = np.loadtxt('D:\\BÀI TẬP\\BÀI TẬP CHƯƠNG 3\\Bài 3.8\\heights.txt',delimiter=',',encoding='utf-8-sig',dtype=float)
np_height

array([191., 184., 185., ..., 183., 179., 179.])

In [22]:
position = np.reshape(np_posistion,(-1,1))
heights = np.reshape(np_height,(-1,1))

In [23]:
arr = np.hstack((position,heights))
arr

array([['GK', '191.0'],
       ['M', '184.0'],
       ['A', '185.0'],
       ...,
       ['D', '183.0'],
       ['D', '179.0'],
       ['M', '179.0']], dtype='<U32')

In [25]:
mask = arr[:,0] =='GK'
arr_gk =arr[mask]

In [28]:
arr_height_gk = arr_gk[:,1].astype(float)
arr_height_gk

array([191., 193., 190., 185., 188., 187., 189., 196., 190., 189., 188.,
       189., 188., 188., 190., 193., 181., 191., 193., 190., 183., 183.,
       193., 193., 196., 184., 190., 186., 195., 191., 187., 185., 186.,
       185., 186., 190., 185., 185., 187., 188., 188., 186., 187., 193.,
       183., 185., 190., 186., 182., 191., 194., 191., 194., 188., 185.,
       189., 187., 188., 184., 176., 187., 186., 191., 188., 191., 192.,
       190., 188., 189., 184., 180., 191., 197., 189., 185., 191., 190.,
       190., 185., 186., 186., 189., 193., 182., 189., 188., 190., 191.,
       183., 189., 189., 190., 188., 184., 194., 188., 194., 193., 186.,
       186., 188., 187., 191., 192., 196., 187., 187., 187., 192., 184.,
       189., 184., 185., 187., 202., 190., 185., 182., 188., 188., 195.,
       187., 183., 197., 188., 190., 193., 191., 187., 184., 183., 185.,
       193., 180., 191., 185., 188., 188., 186., 188., 188., 184., 186.,
       189., 193., 194., 183., 178., 184., 190., 18

In [29]:
# chiều cao trung bình gk là:
np.mean(arr_height_gk)

188.23333333333332

In [30]:
#3
mask1 = arr[:,0] != 'GK'
arr_diffrent_gk = arr[mask1]
arr_diffrent_gk

array([['M', '184.0'],
       ['A', '185.0'],
       ['D', '180.0'],
       ...,
       ['D', '183.0'],
       ['D', '179.0'],
       ['M', '179.0']], dtype='<U32')

In [31]:
height_diffrent_gk = arr_diffrent_gk[:,1].astype(float)
height_diffrent_gk

array([184., 185., 180., ..., 183., 179., 179.])

In [32]:
# chiều cao trung bình kh phải GK là
np.mean(height_diffrent_gk)

180.98888467853985

In [37]:
dtype = np.dtype([('position','U5'),('height',float)])
player = np.array(list(zip(np_posistion,np_height)),dtype = dtype)

In [38]:
player

array([('GK', 191.), ('M', 184.), ('A', 185.), ..., ('D', 183.),
       ('D', 179.), ('M', 179.)],
      dtype=[('position', '<U5'), ('height', '<f8')])

In [39]:
player = np.sort(player,order = 'height')
player

array([('M', 158.), ('A', 160.), ('M', 160.), ..., ('A', 203.),
       ('GK', 203.), ('GK', 208.)],
      dtype=[('position', '<U5'), ('height', '<f8')])

In [40]:
print("vị trí chiều cao cao nhất: ",player[-1])

vị trí chiều cao cao nhất:  ('GK', 208.)


In [41]:
print("vị trí chiều cao thấp nhất: ",player[0])


vị trí chiều cao thấp nhất:  ('M', 158.)
